version: '3'
services:
  bionic:
    build:
      context: ./ubuntu-bionic
      dockerfile: Dockerfile
      args:
        PASSWORD: "docker"
    container_name: bionic
    privileged: true
    volumes:
      - '${HOME}/share_docker:/home/docker/share_docker'
      - '${HOME}/.config/pulse:/root/.config/pulse'
    ports:
      - "12321:22"
      - "12322:80"
      - "12323:8080"

  centos:
    build:
      context: ./centos
      dockerfile: Dockerfile
      args:
        PASSWORD: "docker"
    container_name: centos
    privileged: true
    volumes:
      - '${HOME}/share_docker:/home/docker/share_docker'
      - '${HOME}/.config/pulse:/root/.config/pulse'
    ports:
      - "23432:22"
      - "23433:80"
      - "23434:8080"
