services:
  bionic:
    build:
      context: ./ubuntu-bionic
      dockerfile: Dockerfile
      args:
        PASSWORD: "docker"
    container_name: bionic
    privileged: true
    environment:
      - PULSE_SERVER=host.docker.internal:4713
    volumes:
      - ${HOME}/share_docker:/home/docker/share_docker
    ports:
      - "12321:22"
      - "12322:80"
      - "12323:8080"

  blue-onyx:
    build:
      context: ./rocky-blue-onyx
      dockerfile: Dockerfile
      args:
        PASSWORD: "docker"
    container_name: blue-onyx
    privileged: true
    environment:
      - PULSE_SERVER=host.docker.internal:4713
    volumes:
      - ${HOME}/share_docker:/home/docker/share_docker
    ports:
      - "23432:22"
      - "23433:80"
      - "23434:8080"
